# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2bb0a5602466f2868ab0c5de611dea36"
name = "wl-repricer"
application_url = "https://racketworldshopifyapprepricer-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://racketworldshopifyapprepricer-production.up.railway.app/auth/callback"
]
